### ISSUE TITLE
Error when analyzing X-ray tests

### ISSUE THREAD

**Issue by MartinLip** [psi46/MoReWeb#144]
Hello,

I have problems analyzing xray tests with recent versions of moreweb.
ROOT version is 5.34 with python 2.7.

The last working commit is from 15/10/2015 (9752376d50ed16a3a8e65ec9dc8cc9b9fef69660), the first not working thus is 20792bfbd024be0e821e5079595d3bd461ca6ca0.

Error is the following:
```
l_tester@CMSPixelDB:~/moreweb_xray/Analyse$ python2.7 Controller.py 
MORE web analysis script, Revision number 1
GlobalFinalResultsPath: "/home/l_tester/html/moduleproduction_xray/FinalResults/REV001"
error: invalid key: pager.rev-parse --abbrev-ref HEAD
error: invalid key: alias.rev-parse --abbrev-ref HEAD
git: 'rev-parse --abbrev-ref HEAD' is not a git command. See 'git --help'.
INFO: 389 folders found that needs to be analyzed!
INFO: Analyzing folder 1/389 (XRay
AnalyseTestData ['M4704', 'XRayHRQualification', '2016-01-19', '09h58m', '1453197517'] M4704_XRayHRQualification_2016-01-19_09h58m_1453197517
['M4704', 'XRayHRQualification', '2016-01-19', '09h58m', '1453197517'] M4704_XRayHRQualification_2016-01-19_09h58m_1453197517
Extract Tests from config file
        -> appendXRayHighRateTest
done with extraction
Analyze high rate data...
Import failed:
 importdir:  TestResultClasses.CMSPixel.QualificationGroup.XRayHRQualification.Chips.Chip.EfficiencyInterpolation.TestResult
 fromlist: []

Traceback (most recent call last):
  File "Controller.py", line 623, in <module>
    AnalyseAllTestDataInDirectory(GlobalDataDirectory)
  File "Controller.py", line 417, in AnalyseAllTestDataInDirectory
    AnalyseTestData(ModuleInformationRaw,Folder)
  File "Controller.py", line 342, in AnalyseTestData
    ModuleTestResult = GetModuleTestResult(TestResultEnvironment,FinalModuleResultsPath,ModuleInformation)
  File "Controller.py", line 307, in GetModuleTestResult
    InitialAttributes = newModuleInformation
  File "/home/l_tester/moreweb_xray/Analyse/AbstractClasses/GeneralTestResult.py", line 298, in __init__
    i['DisplayOptions']
  File "/home/l_tester/moreweb_xray/Analyse/AbstractClasses/GeneralTestResult.py", line 298, in __init__
    i['DisplayOptions']
  File "/home/l_tester/moreweb_xray/Analyse/AbstractClasses/GeneralTestResult.py", line 298, in __init__
    i['DisplayOptions']
  File "/home/l_tester/moreweb_xray/Analyse/AbstractClasses/GeneralTestResult.py", line 280, in __init__
    f = __import__(importdir + '.TestResult', fromlist=[''])
  File "/home/l_tester/root/lib/ROOT.py", line 301, in _importhook
    return _orig_ihook( name, *args, **kwds )
ImportError: No module named TestResult
l_tester@CMSPixelDB:~/moreweb_xray/Analyse$ 
```

Also with ROOT v6 the problem is the same .

Do you have any suggestions?

Greetings,
Martin

**Comment by piberger** [comment]
Hi Martin, 

I guess it is because numpy module is not installed, which is shadowed by the ROOT _importhook which claims TestResult to be the module not found.

Try latest commit where I replaced 'numpy' module by 'array' module.

**Comment by MartinLip** [comment]
Hi Pirmin,

thanks, it seems to fix the issue.
